### ISSUE TITLE
Error in plot(tracula) example.

### ISSUE THREAD

**Issue by iPsych** [LCBC-UiO/ggsegTracula#2]
Hello, I got below error in Tracula. (sf is the latest version(1.0.8))
Error in CPL_geos_is_empty(st_geometry(x)) : 
  Evaluation error: IllegalArgumentException: Points of LinearRing do not form a closed linestring.

Tracula3d works well.

**Comment by drmowinckels** [comment]
Hi!

This is a known error for the volumetric based atlases. I am working on a fix, but its going to take a while.

But for now, you can still use the ol `ggseg()` function to plot these data, in stead of the newer `geom_brain()`.


``` r
library(ggseg)
library(ggsegTracula)
#> Warning: package 'ggsegTracula' was built under R version 4.2.1
library(ggplot2)

ggseg(atlas = tracula)
```

![](https://i.imgur.com/q2PZV9z.png)

``` r

ggplot() + 
  geom_brain(atlas = tracula)
#> Error in CPL_geos_is_empty(st_geometry(x)): Evaluation error: IllegalArgumentException: Points of LinearRing do not form a closed linestring.
```

<sup>Created on 2022-09-28 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>
