### ISSUE TITLE
BUG: 3D Fmajor/Fminor are flipped.

### ISSUE THREAD

**Issue by l-espana** [LCBC-UiO/ggsegTracula#3]
Hi,

Not sure if this project is being maintained, but we've noticed the in the tracula_3d atlas the Fmajor and Fminor geometries appear to be flipped. Not sure of the best way to implement a fix.

**Comment by drmowinckels** [comment]
Hi!

when you say flipped, you mean the labels are swapped or that the actual geometries are incorrectly placed?

**Comment by l-espana** [comment]
Hello!
The actual geometries are incorrect. The one labeled Fmajor is actually Fminor and vice versa.

**Comment by drmowinckels** [comment]
ok. That's what i meant with the labels being incorrect. If the structure looks correct, but the label for the structure is incorrect, that is a very easy thing to fix. And I'll get to that asap.

**Comment by drmowinckels** [comment]
Hi. Looking into this, the labels are correct as I see them. The forceps minor connecting the frontal lobes (https://radiopaedia.org/articles/forceps-minor), and the frceps major connecting the occipital lobes (https://radiopaedia.org/articles/forceps-major).

![image](https://github.com/ggseg/ggsegTracula/assets/14014329/e2c833e5-ae12-4cfb-a2a5-1814aa561096)

**Comment by l-espana** [comment]
Yes, so in the 2d version it's fine. If you plot in 3d the geometries are in the wrong location.

**Comment by drmowinckels** [comment]
ok, that soooo weird. Sorry for not catching you meant 3d! Good catch.

![Screenshot 2024-01-03 at 14 02 24](https://github.com/ggseg/ggsegTracula/assets/14014329/5cd74a88-a9a8-4512-ba2e-ec34d5df28c6)

**Comment by l-espana** [comment]
Yes! My PI figured it out...took us a while to understand what was going on ha.

**Comment by drmowinckels** [comment]
The fix has been implemented, let me know how that works for you! it's gonna take a couple of hours for the R-Universe to have the new version built an ready. 

Once [This page](https://ggseg.r-universe.dev/ggsegTracula) shows version `1.0.1.002` then the new version is ready to be installed and you can test with:

```r
# Enable this universe
options(repos = c(
    ggseg = 'https://ggseg.r-universe.dev',
    CRAN = 'https://cloud.r-project.org'))

# Install some packages
install.packages('ggsegTracula')
```

**Comment by l-espana** [comment]
Looks great! Thanks for the fix!!! (Sorry, thought I responded ages ago, ha).
